version: 2
jobs:
  build:
    docker:
    - image: ghcr.io/cybozu/golang:1.20-jammy
    working_directory: /work
    steps:
    - checkout
    - run: test -z "$(gofmt -s -l . | grep -v '^vendor' | tee /dev/stderr)"
    - run: golint -set_exit_status .
    - run: go build ./...
    - run: go test -race -v ./...
    - run: go vet ./...

workflows:
  version: 2
  main:
    jobs:
      - build
